---
apiVersion: v1
kind: ConfigMap
metadata:
  name: apienv
data:
  RHOST: ocidb
  RPORT: "6379"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: oci-config
data:
  config: |
    [myprofile]
    user=ocid1.user.oc1..aaaaaaaaiarn7vrn62bzfvvjbkvhdmihwsfrenw9zve7oexm3b2jm6tbaoja
    fingerprint=ec:94:61:1d:c7:9b:26:40:f2:f1:fa:87:db:21:0a:a1
    key_file=/root/oci_api_key.pem
    tenancy=ocid1.tenancy.oc1..aaaaaaaavl4ndgiiefoo2u4a6atlq2czdwyiu5zzb6rzwwpeyt5o2xmtaxwa
    region=us-ashburn-1
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: oci-priv-key
data:
  oci_api_key.pem: |
    Private key in here